# numpy: package for multidimensional array

In [25]:
#shift tab to check document

In [4]:
# Numpy: Numerical python

In [2]:
import numpy as np

In [5]:
list = [2,5,9]

In [7]:
arr1= np.array(list)
arr1

array([2, 5, 9])

In [19]:
print(type((2,5,7)))
arr2=np.array((2,5,7))
arr2

<class 'tuple'>


array([2, 5, 7])

### np.array takes only one argument

In [12]:
list3 = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
arr3=np.array(list2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,19,3)

array([ 2,  5,  8, 11, 14, 17])

In [28]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(13,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
import numpy as np

In [11]:
np.zeros((3,7),int)


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [3]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

### linspace creates 5 elements with equal difference in range 0 to 1

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

### identity matrixx

In [45]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### transpose of array

In [48]:
b=a.T
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### creates random multiple dimensional array between range 0 to 1

In [17]:
np.random.rand(7)

array([0.1156954 , 0.34997406, 0.62244171, 0.46873408, 0.51452846,
       0.17678304, 0.26957306])

In [18]:
np.random.rand(2,4)

array([[0.06586349, 0.5904037 , 0.5072304 , 0.18581179],
       [0.67492958, 0.51459608, 0.40632418, 0.13163054]])

### creates +ive and -ive random multiple dimensional array between range 0 to 1

In [19]:
np.random.randn(2,5)

array([[-0.42188931,  0.85929972, -0.65025117, -1.78303297, -1.96206034],
       [ 0.29590774,  1.29844781,  0.11498361,  0.85296701, -0.8937523 ]])

### gives random integer . 2nd is optional else 2nd arg must be greater than first . 3rd is number of elements 

In [21]:
np.random.randint(87)

86

In [26]:
np.random.randint(9,87)

32

In [30]:
np.random.randint(23,8)

ValueError: low >= high

In [31]:
np.random.randint(14,75,17)

array([15, 29, 24, 66, 22, 67, 66, 55, 20, 31, 17, 34, 72, 65, 36, 19, 38])

In [35]:
arr2= np.random.randint(13,67,25)
arr2

array([29, 25, 36, 23, 49, 40, 31, 48, 63, 64, 43, 55, 46, 19, 44, 59, 39,
       29, 37, 27, 54, 29, 16, 42, 54])

In [40]:
arr3=np.arange(63)

### 9*7 = 63 which is range of array or total length of array else throws errror

In [51]:
arr4=arr3.reshape(9,7)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62]])

In [44]:
arr3.reshape(9,8)

ValueError: cannot reshape array of size 63 into shape (9,8)

In [36]:
arr2.max()

64

### gives index of max element in array

In [37]:
arr2.argmax()

9

### transposed the matrixx

In [52]:
arr5=arr4.T
arr5

array([[ 0,  7, 14, 21, 28, 35, 42, 49, 56],
       [ 1,  8, 15, 22, 29, 36, 43, 50, 57],
       [ 2,  9, 16, 23, 30, 37, 44, 51, 58],
       [ 3, 10, 17, 24, 31, 38, 45, 52, 59],
       [ 4, 11, 18, 25, 32, 39, 46, 53, 60],
       [ 5, 12, 19, 26, 33, 40, 47, 54, 61],
       [ 6, 13, 20, 27, 34, 41, 48, 55, 62]])

In [54]:
sample_array=np.arange(3,79)
sample_array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78])

### multiple assignments to same element at once 

In [56]:
sample_array[3:17]=100
sample_array

array([  3,   4,   5, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78])

In [59]:
sample_array2=sample_array[16:25]
sample_array2

array([100,  20,  21,  22,  23,  24,  25,  26,  27])

In [60]:
sample_array2[:]=220
sample_array2

array([220, 220, 220, 220, 220, 220, 220, 220, 220])